version: '3'
services:
  ### Postgres database for inventory
  db-inventory:
    container_name: db-inventory
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: mauricio
      POSTGRES_PASSWORD: 123456
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431

  ### MySQL database for orders
  db-orders:
    container_name: db-orders
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_orders
      MYSQL_USER: mauricio
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306

  ### Postgres database for products
  db-products:
    container_name: db-products
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: mauricio
      POSTGRES_PASSWORD: 123456
    ports:
      - 5433:5433
    expose:
      - 5433
    command: -p 5433

  ### Postgres database for keycloak
  db-keycloak:
    container_name: db-keycloak
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_keycloak
      POSTGRES_USER: mauricio
      POSTGRES_PASSWORD: 123456
    ports:
      - 5434:5434
    expose:
      - 5434
    command: -p 5434

  ### keycloak
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    command: ["start-dev"]
    ports:
      - 8181:8181
    expose:
      - 8181
    depends_on:
      - db-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db-keycloak
      DB_DATABASE: ms_keycloak
      DB_PORT: 5434
      DB_USER: mauricio
      DB_PASSWORD: 123456
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8181